### PR TITLE
OS-8594 mdb_v8 update for gcc 14

### PR DESCRIPTION
**Pull request by tsoome**
Need to pull mdb_v8-1.4.4 for gcc 14 build.

### CODE REVIEW

**Review by danmcd — COMMENTED** [review]
Please change the line in `.gitignore` to be 1.4.4 as well?

**Comment by danmcd** [comment]
Thank you.  I've been historically bad about that but recently I'm trying to get better (see #136 e.g.).

**Comment by tsoome** [comment]
Build with gcc 14 is ok.

**Review by danmcd — APPROVED** [review]

**Comment by tsoome** [comment]
gmake test outputs posted with issue.

**Review by bahamat — APPROVED** [review]

**Pull request merged**
