### PR TITLE
OS-8584 Introduce gcc14 as the shadow-compiler

### PR DESCRIPTION
**Pull request by tsoome**
we need few patches to get illumos-extra to build with gcc 14.

### CODE REVIEW

**Comment by danmcd** [comment]
Since late-joyent and MNX, I've been trying to use `XXX SmartOS` in places to indicate gross things; makes it easier to `git grep`.

**Review by danmcd — DISMISSED** [review]
Seems clean & compact.

**Comment by danmcd** [comment]
Okay so a couple of things:

1.) Please put how you tested this into the ticket.  E.g. demonstrating `./configure -s gcc14` or `./configure -p gcc14` work and build things.  If you only tested this with gcc14 as shadow, note that.

2.) In the ticket, mention any test results of any PIs you compiled with gcc14, even if we need more work for a gcc14-primary, or even if it was simple smoke testing.  If you only tested this with gcc14 as shadow, this item is moot.

**Comment by tsoome** [comment]
> Okay so a couple of things:
> 
> 1.) Please put how you tested this into the ticket. E.g. demonstrating `./configure -s gcc14` or `./configure -p gcc14` work and build things. If you only tested this with gcc14 as shadow, note that.
> 
> 2.) In the ticket, mention any test results of any PIs you compiled with gcc14, even if we need more work for a gcc14-primary, or even if it was simple smoke testing. If you only tested this with gcc14 as shadow, this item is moot.

issue updated.

**Pull request merged**
