### PR TITLE
OPENSSH BACKPORT - Disable async-signal-unsafe code in 9.7p1

### PR DESCRIPTION
**Pull request by danmcd**
The tourniquet solution.

### CODE REVIEW

**Comment by bahamat** [comment]
OK, so this patch comes from Debian, and the `#if 0` is effectively just cutting that section of code out.

Presumably, `va_start()` and `va_end()` are some sort of mutex, and the only other thing it does is `sshlogv()`...and that seems like it means it won't log these unsuccessful connections that may potentially be attacks.

I think for the hot fix to the existing release, this is a reasonable approach. This will, no doubt, live longer in Debian than it will in SmartOS.

20240711-release will have 9.8p1.

**Comment by jclulow** [comment]
`va_start()` is the beginning of access to variable arguments; see [stdarg(3EXT)](https://illumos.org/man/3EXT/stdarg) etc.

**Comment by danmcd** [comment]
> 20240711-release will have 9.8p1.

Module severe merge-hell problems, yes.

**Comment by danmcd** [comment]
One +1 reviewer will trigger me backporting this to 20240627 and doing all the rebuilds (e.g. sdc-headnode).

**Comment by danmcd** [comment]
Tested:
```
smartos-build-2(~)[0]% ptree `pgrep sshd`
107986 zsched
  116737 /sbin/init
    131045 /usr/lib/ssh/sshd
      131761 /usr/lib/ssh/sshd -R
        131808 /usr/lib/ssh/sshd -R
          131809 -tcsh
            131855 ptree 131045 131761 131808
smartos-build-2(~)[0]% echo "sshsigdie::dis" | pfexec mdb -p 131045
sshsigdie:                      pushl  %ebp
sshsigdie+1:                    movl   %esp,%ebp
sshsigdie+3:                    subl   $0x14,%esp
sshsigdie+6:                    pushl  $0x1
sshsigdie+8:                    call   -0x56d25 <PLT=libc.so.1`_Exit>
smartos-build-2(~)[0]% 
```

For comparison:
```
smartos-build(~)[0]% echo "sshsigdie::dis" | pfexec mdb -p 21986
sshsigdie:                      pushl  %ebp
sshsigdie+1:                    movl   %esp,%ebp
sshsigdie+3:                    subl   $0x8,%esp
sshsigdie+6:                    leal   0x24(%ebp),%eax
sshsigdie+9:                    pushl  %eax
sshsigdie+0xa:                  pushl  0x20(%ebp)
sshsigdie+0xd:                  pushl  0x1c(%ebp)
sshsigdie+0x10:                 pushl  $0x1
sshsigdie+0x12:                 pushl  0x14(%ebp)
sshsigdie+0x15:                 pushl  0x10(%ebp)
sshsigdie+0x18:                 pushl  0xc(%ebp)
sshsigdie+0x1b:                 pushl  0x8(%ebp)
sshsigdie+0x1e:                 call   -0x213   <sshlogv>
sshsigdie+0x23:                 addl   $0x14,%esp
sshsigdie+0x26:                 pushl  $0x1
sshsigdie+0x28:                 call   -0x56f35 <PLT=libc.so.1`_Exit>
smartos-build(~)[0]%
```

**Review by bahamat — APPROVED** [review]

**Pull request merged**
