### PR TITLE
OS-8479 Update OpenSSH to 9.4p1

### PR DESCRIPTION
**Pull request by danmcd**

### CODE REVIEW

**Comment by danmcd** [comment]
Compare with recent OS-8474 aka illumos-extra#91

**Comment by danmcd** [comment]
WILL need more-than-slight patch adjustments.  Pushing to draft status.

**Comment by danmcd** [comment]
Hmmm, seems to build and at least the client passes the smoke test.

**Comment by danmcd** [comment]
NOTE:  Changes in 0019... are from OmniOS, need to portions-contributed-by credit to Andy F.

**Comment by danmcd** [comment]
So Andy's patch DID have a problem; it didn't used to be a problem, but there's now free() code in the path it patched.  I found it, and he agreed it needed fixing.  I'm running a PI with this on Kebecloud's `curly` right now, and am tempted to put it on the HN as well.

**Review by bahamat — APPROVED** [review]

**Pull request merged**
