### PR TITLE
OS-8592 dialog update for gcc 14

### PR DESCRIPTION
**Pull request by tsoome**
dialog has configure error with gcc 14; in order to check for ncurses.h, it is using tgoto(), but tgoto() is not declared in ncurses.h at all. Use endwin() instead (as it is done in more recent dialog).
gcc 10 does emit warning, but gcc 14 does count it as an error:
`configure:10782:12: warning: implicit declaration of function 'tgoto' [-Wimplicit-function-declaration]`

### CODE REVIEW

**Review by danmcd — COMMENTED** [review]
Can you update the ticket to quickly explain why endwin() is being used by newer `dialog` and why it's okay? (I don't have curses/ncurses wired into my brain.)

**Comment by tsoome** [comment]
> Can you update the ticket to quickly explain why endwin() is being used by newer `dialog` and why it's okay? (I don't have curses/ncurses wired into my brain.)

done. and in short, endwin() is in [n]curses.h, tgoto() is in term.h.

**Comment by danmcd** [comment]
> done. and in short, endwin() is in [n]curses.h, tgoto() is in term.h.

Are they functionally equivalent?

**Review by danmcd — APPROVED** [review]
Dammit I should've realized that.  +1, and please put any testing notes in the ticket for the gcc10 build impact.

**Comment by danmcd** [comment]
IA because it's a change to `configure` not anything else.

**Pull request merged**
