### PR TITLE
OS-8589 openssl1x update for gcc 14

### PR DESCRIPTION
**Pull request by tsoome**
Fix declaration (line 9).
Cast over uintptr_t so the structure size check would not be used.
Add check for array index. Signature algorithms start from 1, so idx > 0 is good check.

### CODE REVIEW

**Review by danmcd — COMMENTED** [review]
Why does this patch name refer to gcc16?

**Review by danmcd — APPROVED** [review]
Please make sure these tests are run before anyone IAs; I can help if need be.

On before-this-patch and after-this-patch with stock gcc10 builds check diffs between

- `dis .../ssl/s3_cbc.o > /tmp/{before,after}`
- `dis .../crypto/bio/b_sock.c`

The t1_lib.c will have altered code, but it seems sensible enough via inspection.

**Review by danmcd — CHANGES_REQUESTED** [review]
This time?

**Comment by tsoome** [comment]
> Why does this patch name refer to gcc16?

This one remains one of the big mysteries about the universe:D Of course, I must have typed 6 instead of 4:)

**Review by danmcd — APPROVED** [review]
What's needed for IA comment still stands.

**Comment by tsoome** [comment]
> Please make sure these tests are run before anyone IAs; I can help if need be.
> 
> On before-this-patch and after-this-patch with stock gcc10 builds check diffs between
> 
> * `dis .../ssl/s3_cbc.o > /tmp/{before,after}`
> * `dis .../crypto/bio/b_sock.c`
> 
> The t1_lib.c will have altered code, but it seems sensible enough via inspection.

no differences:
[tsoome@smartos-dev-21 /tmp]$ diff -u b_sock.before b_sock.after 
[tsoome@smartos-dev-21 /tmp]$ diff -u s3_cbc.before s3_cbc.after 
[tsoome@smartos-dev-21 /tmp]$

**Comment by danmcd** [comment]
Please do not push until after tonight's release branch.

**Pull request merged**
